<?php

namespace Puli;

use Puli\Discovery\Api\Discovery;
use Puli\Discovery\Binding\Initializer\ResourceBindingInitializer;
use Puli\Discovery\JsonDiscovery;
use Puli\Manager\Api\Server\ServerCollection;
use Puli\Repository\Api\ResourceRepository;
use Puli\Repository\JsonRepository;
use Puli\UrlGenerator\Api\UrlGenerator;
use Puli\UrlGenerator\DiscoveryUrlGenerator;
use RuntimeException;

/**
 * Creates Puli's core services.
 *
 * This class was auto-generated by Puli.
 *
 * IMPORTANT: Before modifying the code below, set the "factory.auto-generate"
 * configuration key to false:
 *
 *     $ puli config factory.auto-generate false
 *
 * Otherwise any modifications will be overwritten!
 */
class GeneratedPuliFactory
{
    /**
     * Creates the resource repository.
     *
     * @return ResourceRepository The created resource repository.
     */
    public function createRepository()
    {
        if (!interface_exists('Puli\Repository\Api\ResourceRepository')) {
            throw new RuntimeException('Please install puli/repository to create ResourceRepository instances.');
        }

        $repo = new JsonRepository(__DIR__.'/path-mappings.json', __DIR__.'/..', true);

        return $repo;
    }

    /**
     * Creates the resource discovery.
     *
     * @param ResourceRepository $repo The resource repository to read from.
     *
     * @return Discovery The created discovery.
     */
    public function createDiscovery(ResourceRepository $repo)
    {
        if (!interface_exists('Puli\Discovery\Api\Discovery')) {
            throw new RuntimeException('Please install puli/discovery to create Discovery instances.');
        }

        $discovery = new JsonDiscovery(__DIR__.'/bindings.json', array(
            new ResourceBindingInitializer($repo),
        ));

        return $discovery;
    }

    /**
     * Creates the URL generator.
     *
     * @param Discovery $discovery The discovery to read from.
     *
     * @return UrlGenerator The created URL generator.
     */
    public function createUrlGenerator(Discovery $discovery)
    {
        if (!interface_exists('Puli\UrlGenerator\Api\UrlGenerator')) {
            throw new RuntimeException('Please install puli/url-generator to create UrlGenerator instances.');
        }

        $generator = new DiscoveryUrlGenerator($discovery, array());

        return $generator;
    }

    /**
     * Returns the order in which the installed packages should be loaded
     * according to the override statements.
     *
     * @return string[] The sorted package names.
     */
    public function getPackageOrder()
    {
        $order = array(
            'david/symfony3',
            'clue/stream-filter',
            'container-interop/container-interop',
            'container-interop/service-provider',
            'doctrine/annotations',
            'doctrine/cache',
            'doctrine/collections',
            'doctrine/common',
            'doctrine/dbal',
            'doctrine/doctrine-bundle',
            'doctrine/doctrine-cache-bundle',
            'doctrine/inflector',
            'doctrine/instantiator',
            'doctrine/lexer',
            'doctrine/orm',
            'guzzlehttp/guzzle',
            'guzzlehttp/promises',
            'guzzlehttp/psr7',
            'incenteev/composer-parameter-handler',
            'jdorn/sql-formatter',
            'justinrainbow/json-schema',
            'monolog/monolog',
            'padraic/humbug_get_contents',
            'padraic/phar-updater',
            'paragonie/random_compat',
            'php-http/guzzle6-adapter',
            'php-http/httplug',
            'php-http/message',
            'php-http/message-factory',
            'php-http/promise',
            'psr/cache',
            'psr/http-message',
            'psr/log',
            'puli/cli',
            'puli/composer-plugin',
            'puli/discovery',
            'puli/manager',
            'puli/repository',
            'puli/symfony-bridge',
            'puli/symfony-bundle',
            'puli/url-generator',
            'ramsey/uuid',
            'seld/jsonlint',
            'sensio/distribution-bundle',
            'sensio/framework-extra-bundle',
            'sensio/generator-bundle',
            'sensiolabs/security-checker',
            'swiftmailer/swiftmailer',
            'symfony/monolog-bundle',
            'symfony/phpunit-bridge',
            'symfony/polyfill-apcu',
            'symfony/polyfill-intl-icu',
            'symfony/polyfill-mbstring',
            'symfony/polyfill-php56',
            'symfony/polyfill-php70',
            'symfony/polyfill-util',
            'symfony/swiftmailer-bundle',
            'symfony/symfony',
            'thecodingmachine/common-factories',
            'thecodingmachine/guzzle-universal-service-provider',
            'thecodingmachine/service-provider-bridge-bundle',
            'thecodingmachine/service-provider-registry',
            'thecodingmachine/weatherapi',
            'thecodingmachine/weatherapi-service-provider',
            'twig/twig',
            'webmozart/assert',
            'webmozart/console',
            'webmozart/expression',
            'webmozart/glob',
            'webmozart/json',
            'webmozart/path-util',
        );

        return $order;
    }
}
