<?php

namespace Puli;

use Puli\Discovery\Api\Discovery;
use Puli\Discovery\Binding\Initializer\ResourceBindingInitializer;
use Puli\Discovery\JsonDiscovery;
use Puli\Manager\Api\Server\ServerCollection;
use Puli\Repository\Api\ResourceRepository;
use Puli\Repository\JsonRepository;
use Puli\UrlGenerator\Api\UrlGenerator;
use Puli\UrlGenerator\DiscoveryUrlGenerator;
use RuntimeException;

/**
 * Creates Puli's core services.
 *
 * This class was auto-generated by Puli.
 *
 * IMPORTANT: Before modifying the code below, set the "factory.auto-generate"
 * configuration key to false:
 *
 *     $ puli config factory.auto-generate false
 *
 * Otherwise any modifications will be overwritten!
 */
class GeneratedPuliFactory
{
    /**
     * Creates the resource repository.
     *
     * @return ResourceRepository The created resource repository.
     */
    public function createRepository()
    {
        if (!interface_exists('Puli\Repository\Api\ResourceRepository')) {
            throw new RuntimeException('Please install puli/repository to create ResourceRepository instances.');
        }

        $repo = new JsonRepository(__DIR__.'/path-mappings.json', __DIR__.'/..', true);

        return $repo;
    }

    /**
     * Creates the resource discovery.
     *
     * @param ResourceRepository $repo The resource repository to read from.
     *
     * @return Discovery The created discovery.
     */
    public function createDiscovery(ResourceRepository $repo)
    {
        if (!interface_exists('Puli\Discovery\Api\Discovery')) {
            throw new RuntimeException('Please install puli/discovery to create Discovery instances.');
        }

        $discovery = new JsonDiscovery(__DIR__.'/bindings.json', array(
            new ResourceBindingInitializer($repo),
        ));

        return $discovery;
    }

    /**
     * Creates the URL generator.
     *
     * @param Discovery $discovery The discovery to read from.
     *
     * @return UrlGenerator The created URL generator.
     */
    public function createUrlGenerator(Discovery $discovery)
    {
        if (!interface_exists('Puli\UrlGenerator\Api\UrlGenerator')) {
            throw new RuntimeException('Please install puli/url-generator to create UrlGenerator instances.');
        }

        $generator = new DiscoveryUrlGenerator($discovery, array());

        return $generator;
    }

    /**
     * Returns the order in which the installed packages should be loaded
     * according to the override statements.
     *
     * @return string[] The sorted package names.
     */
    public function getPackageOrder()
    {
        $order = array(
            'laravel/laravel',
            'acclimate/container',
            'classpreloader/classpreloader',
            'clue/stream-filter',
            'container-interop/container-interop',
            'container-interop/service-provider',
            'dnoegel/php-xdg-base-dir',
            'doctrine/inflector',
            'doctrine/instantiator',
            'fzaninotto/faker',
            'guzzlehttp/guzzle',
            'guzzlehttp/promises',
            'guzzlehttp/psr7',
            'hamcrest/hamcrest-php',
            'jakub-onderka/php-console-color',
            'jakub-onderka/php-console-highlighter',
            'jeremeamia/superclosure',
            'justinrainbow/json-schema',
            'laravel/framework',
            'league/flysystem',
            'mnapoli/simplex',
            'mockery/mockery',
            'monolog/monolog',
            'mtdowling/cron-expression',
            'nesbot/carbon',
            'nikic/php-parser',
            'padraic/humbug_get_contents',
            'padraic/phar-updater',
            'paragonie/random_compat',
            'php-http/guzzle6-adapter',
            'php-http/httplug',
            'php-http/message',
            'php-http/message-factory',
            'php-http/promise',
            'phpdocumentor/reflection-common',
            'phpdocumentor/reflection-docblock',
            'phpdocumentor/type-resolver',
            'phpspec/prophecy',
            'phpunit/php-code-coverage',
            'phpunit/php-file-iterator',
            'phpunit/php-text-template',
            'phpunit/php-timer',
            'phpunit/php-token-stream',
            'phpunit/phpunit',
            'phpunit/phpunit-mock-objects',
            'psr/cache',
            'psr/http-message',
            'psr/log',
            'psy/psysh',
            'puli/cli',
            'puli/composer-plugin',
            'puli/discovery',
            'puli/manager',
            'puli/repository',
            'puli/url-generator',
            'ramsey/uuid',
            'sebastian/comparator',
            'sebastian/diff',
            'sebastian/environment',
            'sebastian/exporter',
            'sebastian/global-state',
            'sebastian/recursion-context',
            'sebastian/version',
            'seld/jsonlint',
            'swiftmailer/swiftmailer',
            'symfony/console',
            'symfony/css-selector',
            'symfony/debug',
            'symfony/dom-crawler',
            'symfony/event-dispatcher',
            'symfony/filesystem',
            'symfony/finder',
            'symfony/http-foundation',
            'symfony/http-kernel',
            'symfony/polyfill-mbstring',
            'symfony/polyfill-php56',
            'symfony/polyfill-util',
            'symfony/process',
            'symfony/routing',
            'symfony/translation',
            'symfony/var-dumper',
            'symfony/yaml',
            'tedivm/stash',
            'thecodingmachine/common-factories',
            'thecodingmachine/guzzle-universal-service-provider',
            'thecodingmachine/laravel-universal-service-provider',
            'thecodingmachine/stash-universal-module',
            'thecodingmachine/weatherapi',
            'thecodingmachine/weatherapi-service-provider',
            'vlucas/phpdotenv',
            'webmozart/assert',
            'webmozart/console',
            'webmozart/expression',
            'webmozart/glob',
            'webmozart/json',
            'webmozart/path-util',
        );

        return $order;
    }
}
